import http from'node:http';import{readFile,writeFile,stat,mkdir}from'node:fs/promises';import{createReadStream}from'node:fs';import{extname,join,normalize,resolve}from'node:path';import{randomBytes}from'node:crypto';import{WebSocketServer}from'ws';import{spawn}from'node:child_process';import{argsOf}from'./shared.mjs';import{fileURLToPath}from'node:url';

const args=argsOf(process.argv.slice(2)),root=resolve(fileURLToPath(new URL('../../',import.meta.url))),engine=join(root,'engine'),projectFile=join(engine,'data/project.json'),port=Number(args.port||process.env.PORT||4173),host='127.0.0.1',token=randomBytes(24).toString('hex'),eventDir=join(root,'.motionloom/live/events'),replyDir=join(root,'.motionloom/live/replies');await mkdir(eventDir,{recursive:true});await mkdir(replyDir,{recursive:true});let project=JSON.parse(await readFile(projectFile,'utf8'));let clients=new Set();
const mime={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.json':'application/json','.css':'text/css','.png':'image/png','.map':'application/json'};
function send(res,code,data,type='application/json'){res.writeHead(code,{'content-type':type,'cache-control':'no-store','x-content-type-options':'nosniff'});res.end(type==='application/json'?JSON.stringify(data):data)}
async function body(req){let s='';for await(const c of req){s+=c;if(s.length>1e6)throw Error('body too large')}return JSON.parse(s||'{}')}
async function save(){await writeFile(projectFile,JSON.stringify(project,null,2)+'\n')}
function validatePatch(p){if(!p||!['object','shot'].includes(p.kind)||typeof p.id!=='string'||!p.values||typeof p.values!=='object')throw Error('invalid patch');for(const k of Object.keys(p.values))if(['__proto__','constructor','prototype'].includes(k))throw Error('unsafe key')}
async function patch(p){validatePatch(p);const lookup=Array.isArray(project.objects)?Object.fromEntries(project.objects.map(o=>[o.id,o])):project.objects;const target=p.kind==='object'?lookup[p.id]:project.shots.find(s=>s.id===p.id);if(!target)throw Error('target not found');const duration=Number(project?.meta?.duration ?? project?.canvas?.duration ?? 10);Object.assign(target,p.values);if(p.kind==='shot'){project.shots.sort((a,b)=>a.start-b.start);for(const s of project.shots)if(!(s.end>s.start&&s.start>=0&&s.end<=duration))throw Error('invalid shot time')}await save();broadcast({type:'project.updated',project})}
function broadcast(v){const s=JSON.stringify(v);for(const c of clients)if(c.readyState===1)c.send(s)}
async function queueEvent(message,context){const id=`evt_${Date.now()}_${randomBytes(3).toString('hex')}`,event={id,type:'steer',createdAt:new Date().toISOString(),message,context,status:'pending'};await writeFile(join(eventDir,`${id}.json`),JSON.stringify(event,null,2));broadcast({type:'event.queued',id});return event}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${host}:${port}`);if(req.method==='GET'&&url.pathname==='/api/project')return send(res,200,project);if(req.method==='POST'&&url.pathname==='/api/patch'){const b=await body(req);await patch(b.patch);return send(res,200,{ok:true,project})}if(req.method==='POST'&&url.pathname==='/api/steer'){const b=await body(req),event=await queueEvent(b.message,b.context);return send(res,202,{ok:true,event})}let rel=url.pathname==='/'?'index.html':url.pathname.replace(/^\//,'');let base=engine;if(rel.startsWith('node_modules/'))base=root;const path=normalize(join(base,rel));if(!path.startsWith(base))return send(res,403,{error:'forbidden'});const s=await stat(path);if(s.isDirectory())return send(res,404,{error:'not_found'});res.writeHead(200,{'content-type':mime[extname(path)]||'application/octet-stream','cache-control':'no-store'});createReadStream(path).pipe(res)}catch(e){send(res,e.code==='ENOENT'?404:400,{error:e.message})}});
const wss=new WebSocketServer({noServer:true});server.on('upgrade',(req,socket,head)=>{const url=new URL(req.url,`http://${host}:${port}`);const origin=req.headers.origin||'';if(url.pathname!=='/live'||!origin.startsWith(`http://${host}:${port}`)&&!origin.startsWith(`http://localhost:${port}`)){socket.destroy();return}wss.handleUpgrade(req,socket,head,ws=>wss.emit('connection',ws,req))});wss.on('connection',ws=>{clients.add(ws);ws.send(JSON.stringify({type:'project.updated',project}));ws.on('message',async raw=>{try{const m=JSON.parse(raw);if(m.type==='project.patch')await patch(m.patch);if(m.type==='agent.steer')await queueEvent(m.message,m.context)}catch(e){ws.send(JSON.stringify({type:'error',message:e.message}))}});ws.on('close',()=>clients.delete(ws))});
server.listen(port,host,async()=>{await writeFile(join(root,'.motionloom/live/session.json'),JSON.stringify({pid:process.pid,host,port,token,startedAt:new Date().toISOString()},null,2));console.log(`MotionLoom Live: http://${host}:${port}`);console.log(`Claude event loop: npm run live:poll`);if(args.open){const cmd=process.platform==='win32'?'cmd':process.platform==='darwin'?'open':'xdg-open',argv=process.platform==='win32'?['/c','start','',`http://${host}:${port}`]:[`http://${host}:${port}`];spawn(cmd,argv,{detached:true,stdio:'ignore'}).unref()}});
