import puppeteer from 'puppeteer-core'; import { spawn, spawnSync } from 'node:child_process'; import { mkdirSync, rmSync, writeFileSync } from 'node:fs'; import { dirname, resolve } from 'node:path'; import { fileURLToPath } from 'node:url';
import { argsOf, findChrome, sleep } from './shared.mjs';
const args=argsOf(process.argv.slice(2)); const root=resolve(fileURLToPath(new URL('../',import.meta.url))); const html=`file://${root}/studio.html?play=0`; const chrome=findChrome(args.chrome);
const browser=await puppeteer.launch({executablePath:chrome,headless:true,args:['--no-sandbox','--allow-file-access-from-files','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage(); await page.setViewport({width:1280,height:720,deviceScaleFactor:1}); await page.goto(html,{waitUntil:'networkidle0'}); await page.waitForFunction(()=>window.__motionloom?.ready); const project=await page.evaluate(()=>window.__motionloom.PROJECT);
async function frame(t,path){await page.evaluate(t=>window.__motionloom.renderAt(t),t); await sleep(25); const data=await page.$eval('canvas',c=>c.toDataURL('image/png').split(',')[1]); writeFileSync(path,Buffer.from(data,'base64'));}
function times(s){return String(s).split(',').map(Number)}
async function contact(ts,out,cols=3){const tmp=resolve('out/.motionloom-contact');rmSync(tmp,{recursive:true,force:true});mkdirSync(tmp,{recursive:true});for(let i=0;i<ts.length;i++)await frame(ts[i],`${tmp}/${String(i).padStart(4,'0')}.png`);mkdirSync(dirname(resolve(out)),{recursive:true});const tileW=480,tileH=270,rows=Math.ceil(ts.length/cols);const input=`${tmp}/%04d.png`;const vf=`scale=${tileW}:${tileH},tile=${cols}x${rows}:padding=8:margin=12`;const r=spawnSync('ffmpeg',['-y','-loglevel','error','-framerate','1','-i',input,'-vf',vf,'-frames:v','1',resolve(out)],{stdio:'inherit'});if(r.status)process.exit(r.status);rmSync(tmp,{recursive:true,force:true});}
if(args.still!==undefined){const out=args.out||'out/still.png';mkdirSync(dirname(resolve(out)),{recursive:true});await frame(Number(args.still),resolve(out));console.log(out)}
else if(args.sheet){await contact(times(args.sheet),args.out||'out/contact.png',Number(args.cols||3));console.log(args.out||'out/contact.png')}
else if(args.strip){const[a,b]=String(args.strip).split(':').map(Number),ts=[];for(let f=Math.round(a*project.fps);f<=Math.round(b*project.fps);f++)ts.push(f/project.fps);await contact(ts,args.out||'out/strip.png',Number(args.cols||6));console.log(args.out||'out/strip.png')}
else if(args.video){const out=resolve(args.out||'out/video.mp4');mkdirSync(dirname(out),{recursive:true});const ff=spawn('ffmpeg',['-y','-loglevel','error','-f','image2pipe','-framerate',String(project.fps),'-c:v','png','-i','-','-c:v','libx264','-pix_fmt','yuv420p','-movflags','+faststart',out],{stdio:['pipe','inherit','inherit']});for(let f=0;f<Math.round(project.duration*project.fps);f++){const t=f/project.fps;await page.evaluate(t=>window.__motionloom.renderAt(t),t);await sleep(5);const data=await page.$eval('canvas',c=>c.toDataURL('image/png').split(',')[1]);ff.stdin.write(Buffer.from(data,'base64'));if(f%project.fps===0)process.stdout.write(`\r${t.toFixed(0)}s / ${project.duration}s`)}ff.stdin.end();await new Promise((res,rej)=>ff.on('close',c=>c?rej(new Error(`ffmpeg ${c}`)):res()));console.log(`\n${out}`)}
else console.log('Use --still=SECONDS, --sheet=t1,t2, --strip=a:b, or --video');
await browser.close();
